### ISSUE TITLE
Input Data

### ISSUE THREAD

**Issue by amaik** [yangliuy/TopicExpertiseModel#2]
What is the format I need for the Data, when I first read them into a Documents object. I found out that the preprocessing is done in the Constructor of the Document class. Do I need another preprocessing before calling the constructor or I can I leave the Stack-Overflow *.xml files? How does the folder structure look like, the calls in the code, for example TEMModelSampling.java seem to be different than the structure that is provided in the Dropbox example.

**Comment by yangliuy** [comment]
Sorry for the confusion! If you take a look at https://github.com/yangliuy/TopicExpertiseModel/blob/master/src/tem/main/TEMModelSampling.java, the main function did the following:
1. line 132 getParametersFromFile(modelparam, parameterFile);  COMMENT: load parameters from file
2. line 136 // docSet.readDocs(originalDocsPath, minPostNum);    COMMENT: This is the preprocessing step. You just need to run this function once. It will preprocess the Stack Overflow data and save the processed data into the java serialization object data. That is why I commented this function. Because I already run this function and I just need to load serialized data in line 139. If you didn't run this step, you should run this line to generate the preprocessed serialized data.
3. Generate some data statistics for the data. (line 200 to line 214)
4. The main training process of TEM: model initialization, model inference and model saving, which is correponding to line 216 to line 222. 
5. Finally the model will also be saved as a java serialized data so that you can use this model file for testing phase. (line 226)

Feel free to add more questions if you have :)

**Comment by amaik** [comment]
When trying to read the documents with 

> line 136 // docSet.readDocs(originalDocsPath, minPostNum); COMMENT: This is the preprocessing step. You just need to run this function once. It will preprocess the Stack Overflow data and save the processed data into the java serialization object data. That is why I commented this function. Because I already run this function and I just need to load serialized data in line 139. If you didn't run this step, you should run this line to generate the preprocessed serialized data.

The folder structure is expected to be : originalDataFolder/USER<minPostNum>/posts/
And this folder is supposed to contain *.posts files.

Is there a way to transform the data that I can download from StackOverflow, namely the files that are in the folder: 

> Stack Overflow - Data Dump: August 2010
 - Format: 7zipped 
 - Files:
   - **badges**.xml
   - **comments**.xml
   - **posts**.xml
   - **users**.xml
   - **votes**.xml 

To this *.posts format?

**Comment by yangliuy** [comment]
Yes, there are some open source scripts which can help you import these SO dump file into a MySQL database. Then you can export the data from DB. Here is one example: https://gist.github.com/tundo91/1e074af39d90629252a7df3fc1066397

Another choice is to parse these XML files by yourself. But I recommend the first option, which can save your time.

**Comment by amaik** [comment]
Thanks a lot for your help, I really appreciate it, works like a charm. 

I also found that the scripts, **ExportExpCorpusFromDB** and **ExportTagsFromDB** in tem.script basically do all this work already, which is very good. My problem is now with the testing data. I cannot find where 

`String questionFile = testDataFolder + "testData.questions";
String questionIDFile = testDataFolder + "testDataQuestions.id";`

these files are ever written? Where is the testData split from the rest? Or was this all done manually?

**Comment by yangliuy** [comment]
You can check the test data here: https://www.dropbox.com/sh/42vei96g0vf56dy/AAATUsvDMq7uXkkPsDF87K5pa?dl=0
